import os

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QUrl
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QFileDialog
from menu import Ui_Main


class Ui_LoadData(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Main()
        self.ui.setupUi(self.window)
        pathReport = self.textEdit.toPlainText()
        pathDeTable = self.textEdit_2.toPlainText()
        pathDeHeatmap = self.textEdit_3.toPlainText()
        pathDeVolcano = self.textEdit_4.toPlainText()
        pathDePCA = self.textEdit_5.toPlainText()
        pathGOTable = self.textEdit_6.toPlainText()
        pathEnrichment = self.textEdit_7.toPlainText()
        pathBarPlot = self.textEdit_8.toPlainText()
        if pathReport:
            pathReport.replace("\\", "/")
            self.ui.webView.setUrl(QUrl("file:///" + pathReport))
        if pathDeTable:
            self.ui.loadDeTable(pathDeTable)
        if pathDeHeatmap:
            self.ui.pixmap = QPixmap(pathDeHeatmap)
            self.ui.label_4.setPixmap(self.ui.pixmap)
        if pathDeVolcano:
            self.ui.pixmap2 = QPixmap(pathDeVolcano)
            self.ui.label_3.setPixmap(self.ui.pixmap2)
        if pathDePCA:
            self.ui.pixmap3 = QPixmap(pathDePCA)
            self.ui.label_2.setPixmap(self.ui.pixmap3)
        if pathGOTable:
            self.ui.loadGoTable(pathGOTable)
        if pathEnrichment:
            self.ui.pixmap4 = QPixmap(pathEnrichment)
            self.ui.label_6.setPixmap(self.ui.pixmap4)
        if pathBarPlot:
            self.ui.pixmap5 = QPixmap(pathBarPlot)
            self.ui.label_5.setPixmap(self.ui.pixmap5)


        self.window.show()

    def browseFile(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'PDF File (*.pdf)')
        self.textEdit.setText(fname[0])

    def browseGeneExpression(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), "CSV Files (*.csv);; TSV Files (*.tsv);; "
                                                                     "TXT Files (*.txt) ;; TAB Files (*.tab)")
        self.textEdit_2.setText(fname[0])

    def browseHeatmap(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'SVG File (*.svg)')
        self.textEdit_3.setText(fname[0])

    def browseVolcano(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'SVG File (*.svg)')
        self.textEdit_4.setText(fname[0])

    def browsePCA(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'SVG File (*.svg)')
        self.textEdit_5.setText(fname[0])

    def browseGOTable(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'),
                                            "CSV Files (*.csv);; TSV Files (*.tsv);; "
                                            "TXT Files (*.txt) ;; TAB Files (*.tab)")
        self.textEdit_6.setText(fname[0])

    def browseGOEnrichment(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'SVG File (*.svg)')
        self.textEdit_7.setText(fname[0])

    def browseGOBarplot(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'SVG File (*.svg)')
        self.textEdit_8.setText(fname[0])

    def checkIfFilled(self):
        if (self.textEdit.toPlainText() == '' and self.textEdit_2.toPlainText() == '' and self.textEdit_3.toPlainText() == ''
                and self.textEdit_4.toPlainText() == '' and self.textEdit_5.toPlainText() == '' and self.textEdit_6.toPlainText() == ''
                and self.textEdit_7.toPlainText() == '' and self.textEdit_8.toPlainText() == '' and self.textEdit_9.toPlainText() == ''
                and self.textEdit_10.toPlainText() == ''):
            self.pushButton_6.setDisabled(True)
        else:
            self.pushButton_6.setDisabled(False)

    def setupUi(self, LoadWindow):
        LoadWindow.setObjectName("MainWindow")
        LoadWindow.setFixedSize(650, 900)
        self.centralwidget = QtWidgets.QWidget(parent=LoadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 560, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.label.setMinimumWidth(180)
        self.horizontalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setMinimumWidth(250)
        self.textEdit.setPlaceholderText("Optional: Path to Report")
        self.textEdit.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout.addWidget(self.textEdit)
        self.textEdit.setDisabled(True)
        self.pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.browseFile)
        self.pushButton.setMaximumWidth(100)
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 120, 560, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.label_2.setMinimumWidth(180)
        self.horizontalLayout_2.addWidget(self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_2)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setPlaceholderText("Optional Path to Table for Gene Expression Data")
        self.textEdit_2.setMinimumWidth(250)
        self.textEdit_2.textChanged.connect(self.checkIfFilled)
        self.textEdit_2.setDisabled(True)
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setMaximumWidth(100)
        self.pushButton_2.clicked.connect(self.browseGeneExpression)
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 190, 560, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.label_3.setMinimumWidth(180)
        self.horizontalLayout_3.addWidget(self.label_3)
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_3)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setPlaceholderText("Optional: Path to Heatmap")
        self.textEdit_3.setMinimumWidth(250)
        self.textEdit_3.textChanged.connect(self.checkIfFilled)
        self.textEdit_3.setDisabled(True)
        self.horizontalLayout_3.addWidget(self.textEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setMaximumWidth(100)
        self.pushButton_3.clicked.connect(self.browseHeatmap)
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 260, 560, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.label_4.setMinimumWidth(180)
        self.horizontalLayout_4.addWidget(self.label_4)
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_4)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_4.setPlaceholderText("Optional: Path to Volcano Plot")
        self.textEdit_4.setMinimumWidth(250)
        self.textEdit_4.textChanged.connect(self.checkIfFilled)
        self.textEdit_4.setDisabled(True)
        self.horizontalLayout_4.addWidget(self.textEdit_4)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.browseVolcano)
        self.pushButton_4.setMaximumWidth(100)
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 330, 560, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.label_5.setMinimumWidth(180)
        self.horizontalLayout_5.addWidget(self.label_5)
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_5)
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_5.setPlaceholderText("Optional: Path to PCA")
        self.textEdit_5.setMinimumWidth(250)
        self.textEdit_5.setDisabled(True)
        self.textEdit_5.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout_5.addWidget(self.textEdit_5)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setMaximumWidth(100)
        self.pushButton_5.clicked.connect(self.browsePCA)
        self.horizontalLayout_5.addWidget(self.pushButton_5)

        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(50, 400, 560, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_6)
        self.label_7.setObjectName("label_7")
        self.label_7.setMinimumWidth(180)
        self.horizontalLayout_6.addWidget(self.label_7)
        self.textEdit_6 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_6)
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_6.setPlaceholderText("Optional: GSEA Term Table")
        self.textEdit_6.setMinimumWidth(250)
        self.textEdit_6.setDisabled(True)
        self.textEdit_6.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout_6.addWidget(self.textEdit_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.pushButton_7.setObjectName("pushButton_5")
        self.pushButton_7.setMaximumWidth(100)
        self.pushButton_7.clicked.connect(self.browseGOTable)
        self.horizontalLayout_6.addWidget(self.pushButton_7)

        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(50, 470, 560, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.label_8.setMinimumWidth(180)
        self.horizontalLayout_7.addWidget(self.label_8)
        self.textEdit_7 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_7)
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_7.setPlaceholderText("Optional: Path to Enrichment Plot")
        self.textEdit_7.setMinimumWidth(250)
        self.textEdit_7.setDisabled(True)
        self.textEdit_7.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout_7.addWidget(self.textEdit_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.pushButton_8.setObjectName("pushButton_5")
        self.pushButton_8.setMaximumWidth(100)
        self.pushButton_8.clicked.connect(self.browseGOEnrichment)
        self.horizontalLayout_7.addWidget(self.pushButton_8)

        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(50, 540, 560, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.label_9.setMinimumWidth(180)
        self.horizontalLayout_8.addWidget(self.label_9)
        self.textEdit_8 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_8)
        self.textEdit_8.setObjectName("textEdit_7")
        self.textEdit_8.setPlaceholderText("Optional: Path to Barplot")
        self.textEdit_8.setMinimumWidth(250)
        self.textEdit_8.setDisabled(True)
        self.textEdit_8.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout_8.addWidget(self.textEdit_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        self.pushButton_9.setObjectName("pushButton_5")
        self.pushButton_9.setMaximumWidth(100)
        self.pushButton_9.clicked.connect(self.browseGOBarplot)
        self.horizontalLayout_8.addWidget(self.pushButton_9)

        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(50, 610, 560, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_9)
        self.label_10.setObjectName("label_9")
        self.label_10.setMinimumWidth(180)
        self.horizontalLayout_9.addWidget(self.label_10)
        self.textEdit_9 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_9)
        self.textEdit_9.setObjectName("textEdit_7")
        self.textEdit_9.setPlaceholderText("Optional: Path to Isoform Expression Table")
        self.textEdit_9.setMinimumWidth(250)
        self.textEdit_9.setDisabled(True)
        self.textEdit_9.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout_9.addWidget(self.textEdit_9)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_9)
        self.pushButton_10.setObjectName("pushButton_5")
        self.pushButton_10.setMaximumWidth(100)
        self.horizontalLayout_9.addWidget(self.pushButton_10)

        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(50, 680, 560, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_10)
        self.label_11.setObjectName("label_9")
        self.label_11.setMinimumWidth(180)
        self.horizontalLayout_10.addWidget(self.label_11)
        self.textEdit_10 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_10)
        self.textEdit_10.setObjectName("textEdit_7")
        self.textEdit_10.setPlaceholderText("Optional: Path to Isoform Heatmap")
        self.textEdit_10.setMinimumWidth(250)
        self.textEdit_10.setDisabled(True)
        self.textEdit_10.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout_10.addWidget(self.textEdit_10)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_10)
        self.pushButton_11.setObjectName("pushButton_5")
        self.pushButton_11.setMaximumWidth(100)
        self.horizontalLayout_10.addWidget(self.pushButton_11)

        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(275, 10, 150, 30))
        self.label_6.setObjectName("label_6")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_6.setFont(font)

        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.clicked.connect(self.openWindow)
        self.pushButton_6.clicked.connect(LoadWindow.close)
        self.pushButton_6.setGeometry(QtCore.QRect(510, 830, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("load_39552.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setDisabled(True)
        LoadWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoadWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 21))
        self.menubar.setObjectName("menubar")
        LoadWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoadWindow)
        self.statusbar.setObjectName("statusbar")
        LoadWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoadWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadWindow)

    def retranslateUi(self, LoadWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadWindow.setWindowTitle(_translate("LoadWindow", "Load Previous Experiment"))
        self.label.setText(_translate("LoadWindow", "Report"))
        self.pushButton.setText(_translate("LoadWindow", "Browse"))
        self.label_2.setText(_translate("LoadWindow", "Gene Expression Table"))
        self.pushButton_2.setText(_translate("LoadWindow", "Browse"))
        self.label_3.setText(_translate("LoadWindow", "DE Heatmap"))
        self.pushButton_3.setText(_translate("LoadWindow", "Browse"))
        self.label_4.setText(_translate("LoadWindow", "DE Volcano"))
        self.pushButton_4.setText(_translate("LoadWindow", "Browse"))
        self.label_5.setText(_translate("LoadWindow", "DE PCA"))
        self.pushButton_5.setText(_translate("LoadWindow", "Browse"))
        self.label_6.setText(_translate("LoadWindow", "Load Data"))
        self.pushButton_6.setText(_translate("LoadWindow", "Load"))
        self.pushButton_7.setText(_translate("LoadWindow", "Browse"))
        self.label_7.setText(_translate("LoadWindow", "GSEA Term Table"))
        self.label_8.setText(_translate("LoadWindow", "GSEA Term Enrichment Plot"))
        self.pushButton_8.setText(_translate("LoadWindow", "Browse"))
        self.label_9.setText(_translate("LoadWindow", "GSEA Term Barplot"))
        self.pushButton_9.setText(_translate("LoadWindow", "Browse"))
        self.label_10.setText(_translate("LoadWindow", "Isoform Expression Table"))
        self.pushButton_10.setText(_translate("LoadWindow", "Browse"))
        self.label_11.setText(_translate("LoadWindow", "Isoform Heatmap"))
        self.pushButton_11.setText(_translate("LoadWindow", "Browse"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_LoadData()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec())