import os

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QUrl
from PyQt6.QtWidgets import QFileDialog
from menu import Ui_Main


class Ui_LoadData(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Main()
        self.ui.setupUi(self.window)
        pathReport = self.textEdit.toPlainText()
        if pathReport:
            pathReport.replace("\\", "/")
            self.ui.webView.setUrl(QUrl("file:///" + pathReport))
        self.window.show()

    def browseFile(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'PDF File (*.pdf)')
        self.textEdit.setText(fname[0])

    def browseGeneExpression(self):
        dialog = QFileDialog()
        dialog.setNameFilter("CSV (*.csv *.tsv *.txt)")
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), "CSV Files (*.csv);; TSV Files (*.tsv);; "
                                                                     "TXT Files (*.txt) ;; TAB Files (*.tab)")
        self.textEdit_2.setText(fname[0])

    def browseHeatmap(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'PDF File (*.pdf)')
        self.textEdit_3.setText(fname[0])

    def browseIsoformSheet(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), 'PDF File (*.pdf)')
        self.textEdit_5.setText(fname[0])

    def browseIsoformTable(self):
        fname = QFileDialog.getOpenFileName(self.centralwidget, "Open file", os.getenv('Home'), "CSV Files (*.csv);; TSV Files (*.tsv);; "
                                                                     "TXT Files (*.txt) ;; TAB Files (*.tab)")
        self.textEdit_4.setText(fname[0])

    def checkIfFilled(self):
        if (self.textEdit.toPlainText() == '' and self.textEdit_2.toPlainText() == '' and self.textEdit_3.toPlainText() == ''
                and self.textEdit_4.toPlainText() == '' and self.textEdit_5.toPlainText() == ''):
            self.pushButton_6.setDisabled(True)
        else:
            self.pushButton_6.setDisabled(False)

    def setupUi(self, LoadWindow):
        LoadWindow.setObjectName("MainWindow")
        LoadWindow.setFixedSize(650, 485)
        self.centralwidget = QtWidgets.QWidget(parent=LoadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 560, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.label.setMinimumWidth(180)
        self.horizontalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setMinimumWidth(250)
        self.textEdit.setPlaceholderText("Optional: Path to Report")
        self.textEdit.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout.addWidget(self.textEdit)
        self.textEdit.setDisabled(True)
        self.pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.browseFile)
        self.pushButton.setMaximumWidth(100)
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 120, 560, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.label_2.setMinimumWidth(180)
        self.horizontalLayout_2.addWidget(self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_2)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setPlaceholderText("Optional Path to Table for Gene Expression Data")
        self.textEdit_2.setMinimumWidth(250)
        self.textEdit_2.textChanged.connect(self.checkIfFilled)
        self.textEdit_2.setDisabled(True)
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setMaximumWidth(100)
        self.pushButton_2.clicked.connect(self.browseGeneExpression)
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 190, 560, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.label_3.setMinimumWidth(180)
        self.horizontalLayout_3.addWidget(self.label_3)
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_3)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setPlaceholderText("Optional: Path to Heatmap")
        self.textEdit_3.setMinimumWidth(250)
        self.textEdit_3.textChanged.connect(self.checkIfFilled)
        self.textEdit_3.setDisabled(True)
        self.horizontalLayout_3.addWidget(self.textEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setMaximumWidth(100)
        self.pushButton_3.clicked.connect(self.browseHeatmap)
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 260, 560, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.label_4.setMinimumWidth(180)
        self.horizontalLayout_4.addWidget(self.label_4)
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_4)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_4.setPlaceholderText("Optional: Path to Isoform Data Table")
        self.textEdit_4.setMinimumWidth(250)
        self.textEdit_4.textChanged.connect(self.checkIfFilled)
        self.textEdit_4.setDisabled(True)
        self.horizontalLayout_4.addWidget(self.textEdit_4)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.browseIsoformTable)
        self.pushButton_4.setMaximumWidth(100)
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 332, 560, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.label_5.setMinimumWidth(180)
        self.horizontalLayout_5.addWidget(self.label_5)
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_5)
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_5.setPlaceholderText("Optional: Path to Isoform Data")
        self.textEdit_5.setMinimumWidth(250)
        self.textEdit_5.setDisabled(True)
        self.textEdit_5.textChanged.connect(self.checkIfFilled)
        self.horizontalLayout_5.addWidget(self.textEdit_5)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setMaximumWidth(100)
        self.pushButton_5.clicked.connect(self.browseIsoformSheet)
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(275, 10, 150, 30))
        self.label_6.setObjectName("label_6")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_6.setFont(font)

        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.clicked.connect(self.openWindow)
        self.pushButton_6.clicked.connect(LoadWindow.close)
        self.pushButton_6.setGeometry(QtCore.QRect(510, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("load_39552.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setDisabled(True)
        LoadWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoadWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 21))
        self.menubar.setObjectName("menubar")
        LoadWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoadWindow)
        self.statusbar.setObjectName("statusbar")
        LoadWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoadWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadWindow)

    def retranslateUi(self, LoadWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadWindow.setWindowTitle(_translate("LoadWindow", "Load Previous Experiment"))
        self.label.setText(_translate("LoadWindow", "Report"))
        self.pushButton.setText(_translate("LoadWindow", "Browse"))
        self.label_2.setText(_translate("LoadWindow", "Gene Expression Table"))
        self.pushButton_2.setText(_translate("LoadWindow", "Browse"))
        self.label_3.setText(_translate("LoadWindow", "Heatmap"))
        self.pushButton_3.setText(_translate("LoadWindow", "Browse"))
        self.label_4.setText(_translate("LoadWindow", "Isoform Table"))
        self.pushButton_4.setText(_translate("LoadWindow", "Browse"))
        self.label_5.setText(_translate("LoadWindow", "Isoform Graphs"))
        self.pushButton_5.setText(_translate("LoadWindow", "Browse"))
        self.label_6.setText(_translate("LoadWindow", "Load Data"))
        self.pushButton_6.setText(_translate("LoadWindow", "Load"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_LoadData()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec())